# Generated by Django 3.2.4 on 2021-06-19 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostFile',
        ),
    ]
