# Generated by Django 3.2.4 on 2021-07-02 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_delete_postfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='content',
        ),
        migrations.RemoveField(
            model_name='person',
            name='extra',
        ),
    ]
