# Generated by Django 3.2.4 on 2021-07-02 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0003_auto_20210702_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='link',
        ),
    ]
