# Generated by Django 3.2.4 on 2021-07-02 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0004_remove_person_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='phone',
        ),
    ]
