# Generated by Django 3.2.4 on 2021-07-03 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0006_auto_20210703_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
