# Generated by Django 3.2.4 on 2021-07-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0007_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='headshot',
            field=models.ImageField(null=True, upload_to='people/'),
        ),
    ]
