# Generated by Django 3.2.4 on 2021-07-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0008_alter_person_headshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='headshot',
            field=models.ImageField(blank=True, null=True, upload_to='people/'),
        ),
    ]
