# Generated by Django 3.2.4 on 2021-07-05 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0010_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='group',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
