# Generated by Django 2.2.13 on 2020-08-04 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_remove_comment_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Photo',
            field=models.ImageField(blank=True, default='media/feedback/image5.jpg', null=True, upload_to='media/feedback'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Priority',
            field=models.CharField(choices=[('BU', 'Bug_urgent'), ('BNU', 'Bug_not_urgent'), ('FT', 'New feature'), ('UX', 'UX_urgent')], default='BNU', max_length=3),
        ),
        migrations.AlterField(
            model_name='task_status',
            name='assigned_to',
            field=models.CharField(choices=[('BR', 'Bhargav Bolla'), ('XJ', 'Xibei Jia')], default='XJ', max_length=2),
        ),
        migrations.AlterField(
            model_name='task_status',
            name='task_status',
            field=models.CharField(choices=[('CO', 'done'), ('WR', 'working'), ('NM', 'need more info'), ('NW', 'New')], default='NW', max_length=2),
        ),
    ]
