version: '3'
    
services:

  web:
    build: ./app

    #****WARNING***** TODO: REMOVE THE FLUSH COMMAND BELOW WITH LIVE DATA, IT WILL LITERALLY DELETE EVERYTHING IN THE DATABASE ****WARNING*****
    #If Django is reporting an issue with relations not existing, this may help, but DO NOT RUN THIS COMMAND IF DJANGO IS IN ANY WAY TIED TO THE ONLY COPY OF THE DATA YOU HAVE. IT WILL INSTANTLY DELETE IT WITH NO BACKUP.
    command: bash -c "python manage.py reset_db --noinput &&
                      echo RESET_DB_FIN &&         
                      python manage.py flush --noinput &&         
                      echo FLUSH_FIN &&
                      python manage.py makemigrations &&
                      echo MAKEMIGRATIONS_FIN &&
                      python manage.py migrate --noinput -v 1 && 
                      echo MIGRATE_FIN &&
                      python manage.py loaddata flatpage.json &&
                      echo LOADDATA_FIN &&
                      python manage.py check &&
                      echo CHECK_FIN &&
                      python manage.py findstatic --verbosity 2 bootstrap-responsive.min.css &&
                      echo FIND_FIN &&
                      gunicorn eomf.wsgi:application --bind 0.0.0.0:8000"
                      #python manage.py runserver 0.0.0.0:8000"

    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000            
    env_file:
      - ./.env
    depends_on:
      - db



  db:
    image: postgis/postgis
    volumes:
      - postgres_data:/var/lib/postgresql/data

    env_file:
      - ./.env.db



  redis:
    image: "redis"
    ports:
      - "6379:6379"



  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 80:80
    depends_on:
      - web
      
volumes:
  postgres_data:
  static_volume: