# Generated by Django 2.2.13 on 2020-08-05 20:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty', models.IntegerField(blank=True, null=True)),
                ('spp', models.CharField(blank=True, max_length=16, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('dutylocs', models.IntegerField(blank=True, null=True)),
                ('second', models.IntegerField(blank=True, null=True)),
                ('lc94', models.CharField(blank=True, max_length=2, null=True)),
                ('mmdd', models.CharField(blank=True, max_length=5, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('jday', models.IntegerField(blank=True, null=True)),
                ('ptt', models.IntegerField(blank=True, null=True)),
                ('deplylon', models.FloatField(blank=True, null=True)),
                ('gspeed', models.CharField(blank=True, max_length=3, null=True)),
                ('gmt_min', models.IntegerField(blank=True, null=True)),
                ('deltahr', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=3, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('animal', models.CharField(blank=True, max_length=14, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('gazm', models.CharField(blank=True, max_length=3, null=True)),
                ('gmt_sec', models.IntegerField(blank=True, null=True)),
                ('ghour', models.IntegerField(blank=True, null=True)),
                ('ddmm', models.CharField(blank=True, max_length=5, null=True)),
                ('gmt_hour', models.IntegerField(blank=True, null=True)),
                ('gmin', models.IntegerField(blank=True, null=True)),
                ('dtime', models.CharField(blank=True, max_length=16, null=True)),
                ('gmt_date', models.CharField(blank=True, max_length=10, null=True)),
                ('deplylat', models.FloatField(blank=True, null=True)),
                ('jd', models.IntegerField(blank=True, null=True)),
                ('line', models.CharField(blank=True, max_length=32, null=True)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('minute', models.IntegerField(blank=True, null=True)),
                ('gelev', models.IntegerField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('hour', models.IntegerField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('nlocrank', models.FloatField(blank=True, null=True)),
                ('daysdply', models.IntegerField(blank=True, null=True)),
                ('thetime', models.CharField(blank=True, max_length=16, null=True)),
                ('azimuth', models.FloatField(blank=True, null=True)),
                ('latest', models.IntegerField(blank=True, null=True)),
                ('first', models.IntegerField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Datatype',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='H5n1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=64)),
                ('admin1', models.CharField(max_length=64)),
                ('admin2', models.CharField(max_length=64, null=True)),
                ('quality', models.CharField(max_length=64, null=True)),
                ('locality', models.CharField(max_length=86)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=10)),
                ('observation_date', models.DateField()),
                ('surveillance_type', models.CharField(max_length=20)),
                ('reporting_date', models.DateField()),
                ('diagnosis_status', models.CharField(max_length=20)),
                ('disease', models.CharField(max_length=40)),
                ('disease_type', models.CharField(max_length=4, null=True)),
                ('species', models.CharField(max_length=256, null=True)),
                ('at_risk', models.IntegerField(null=True)),
                ('cases', models.IntegerField(null=True)),
                ('deaths', models.IntegerField(null=True)),
                ('destroyed', models.IntegerField(null=True)),
                ('slaughtered', models.IntegerField(null=True)),
                ('vaccinated', models.IntegerField(null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Datainfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=100)),
                ('abstract', models.TextField(blank=True)),
                ('label', models.CharField(max_length=100)),
                ('legend', models.BooleanField()),
                ('vector', models.BooleanField()),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('datatype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geohealth.Datatype')),
            ],
        ),
    ]
