# Generated by Django 3.2.12 on 2022-03-16 20:11

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TROPOMIYearFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TROPOMISingleTimeSeriesJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, max_length=50, null=True)),
                ('pixelx', models.IntegerField(blank=True, null=True)),
                ('pixely', models.IntegerField(blank=True, null=True)),
                ('result', models.FileField(blank=True, max_length=300, null=True, upload_to='tropomi/timeseries/single')),
                ('years', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=4), size=None)),
                ('working', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('errored', models.BooleanField(default=False)),
                ('percent_complete', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('user', models.ForeignKey(default=1096, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TROPOMIMultipleTimeSeriesJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, max_length=50, null=True)),
                ('points', models.FileField(max_length=150, upload_to='tropomi/timeseries/multi/input/')),
                ('result', models.FileField(blank=True, max_length=300, null=True, upload_to='tropomi/timeseries/multi/output/')),
                ('years', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=4), size=None)),
                ('working', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('errored', models.BooleanField(default=False)),
                ('percent_complete', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('user', models.ForeignKey(default=1096, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
