# Generated by Django 3.2.12 on 2022-03-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tropomi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tropomimultipletimeseriesjob',
            name='completed_chunks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tropomimultipletimeseriesjob',
            name='errored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tropomimultipletimeseriesjob',
            name='total_chunks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tropomimultipletimeseriesjob',
            name='working',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tropomisingletimeseriesjob',
            name='errored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tropomisingletimeseriesjob',
            name='percent_complete',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tropomisingletimeseriesjob',
            name='working',
            field=models.BooleanField(default=False),
        ),
    ]
