# Generated by Django 2.2.13 on 2020-08-05 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubtype', models.CharField(choices=[('jour', 'Journal'), ('chap', 'Book and Book Chapters'), ('post', 'Posters'), ('pres', 'Presentations')], max_length=4, null=True)),
                ('authorship', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('link', models.CharField(blank=True, max_length=250, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='docs/upload')),
                ('date', models.DateField(null=True, verbose_name='date published')),
                ('journal', models.CharField(blank=True, max_length=125, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=250, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('volume', models.CharField(blank=True, max_length=56, null=True)),
                ('issue', models.CharField(blank=True, max_length=56, null=True)),
                ('pages', models.CharField(blank=True, max_length=56, null=True)),
                ('editors', models.CharField(blank=True, max_length=128, null=True)),
                ('book_title', models.CharField(blank=True, max_length=128, null=True)),
                ('publisher', models.CharField(blank=True, max_length=128, null=True)),
                ('issn', models.CharField(blank=True, max_length=56, null=True)),
                ('doi', models.CharField(blank=True, max_length=56, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Category')),
            ],
        ),
    ]
