# Generated by Django 3.2.15 on 2022-12-07 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
