# Generated by Django 2.2.13 on 2020-08-05 20:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DuckTrack',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('animal', models.CharField(max_length=20)),
                ('ptt', models.CharField(max_length=15)),
                ('record_id', models.CharField(max_length=30)),
                ('datetime', models.DateTimeField()),
                ('days_ago', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=10)),
                ('lc94', models.CharField(max_length=6)),
                ('nmess', models.IntegerField()),
                ('days_dply', models.IntegerField()),
                ('sen1', models.IntegerField()),
                ('sen2', models.IntegerField()),
                ('sen3', models.IntegerField()),
                ('sen4', models.IntegerField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'duck_tracks',
            },
        ),
        migrations.CreateModel(
            name='DuckTrackLine',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('animal', models.CharField(max_length=20)),
                ('location', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
            options={
                'db_table': 'duck_track_line',
            },
        ),
    ]
