# Generated by Django 2.2.13 on 2020-08-24 21:39

from django.db import migrations

from django.conf import settings
from django.db import migrations, models
from django.contrib.flatpages.models import FlatPage
from django.contrib.sites.models import Site

FLATPAGES = [
    {
        "title": "Home",
        "url": "/home/",
        "content": "<div class=\"slideshow\">&nbsp;&nbsp;&nbsp;<img src=\"/media/images/Splash/1.png\">&nbsp;&nbsp;&nbsp; <img src=\"/media/images/Splash/2.png\" >&nbsp;&nbsp;&nbsp; <img src=\"/media/images/Splash/3.png\" >&nbsp;&nbsp;&nbsp; <img src=\"/media/images/Splash/4.png\" >&nbsp;&nbsp;&nbsp; <img src=\"/media/images/Splash/5.png\" >&nbsp;&nbsp;&nbsp; <img src=\"/media/images/Splash/6.png\" ></div>",
        "enable_comments": False,
        "template_name":"home.html",
        "registration_required": False
    },
]


def add_flatpages_data(apps, schema_editor):
    new_site = Site.objects.create(domain='eomf.ou.edu', name='eomf.ou.edu')
    print (new_site.id)
    current_site = Site.objects.get(pk=1)
    for page_dict in FLATPAGES:
        new_page = FlatPage.objects.create(
            title=page_dict['title'],
            url=page_dict['url'],
            content=page_dict['content'],
            enable_comments=page_dict['enable_comments'],
            template_name=page_dict['template_name'],
            registration_required=page_dict['registration_required'],
            )
        new_page.sites.add(current_site)


def remove_flatpages_data(apps, schema_editor):
    for page_dict in FLATPAGES:
        page = FlatPage.objects.get(
            url=page_dict['url'])
        page.delete()

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            add_flatpages_data,
            #remove_flatpages_data,
        ),
    ]
