# Generated by Django 2.2.13 on 2020-08-10 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contentpage',
            table='django_contentpage',
        ),
    ]
