# Generated by Django 2.2.20 on 2021-06-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='notes',
            field=models.TextField(db_column='description', null=True),
        ),
    ]
