# Generated by Django 2.2.20 on 2021-06-07 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20210607_0317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='theme',
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
