# Generated by Django 2.2.20 on 2021-06-07 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20210607_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='datum',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
