# Generated by Django 2.2.20 on 2021-06-07 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_auto_20210607_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.ForeignKey(blank=True, db_column='categoryid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='photos.Category'),
        ),
    ]
