# Generated by Django 3.2.4 on 2021-08-24 12:18

import ceom.photos.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_auto_20210610_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(blank=True, db_column='location', max_length=300, storage=django.core.files.storage.FileSystemStorage(base_url='/media/photos/', location='/code/app/ceom/media/photos'), upload_to=ceom.photos.models.photo_path),
        ),
    ]
