# Generated by Jonathan

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0011_categoryvote'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO photos_categoryvote (photoid, userid, categoryid)
            SELECT id, userid, categoryid FROM photos WHERE categoryid IS NOT NULL AND categoryid != 0;
        """),
    ]
