# Generated by Django 2.2.13 on 2020-08-04 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_dataset_is_global'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='absolute_path',
            field=models.CharField(default='N/A', max_length=300),
        ),
        migrations.AlterField(
            model_name='process',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date processed'),
        ),
    ]
