# Generated by Django 2.2.13 on 2020-08-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=250)),
                ('funding_agency', models.CharField(blank=True, max_length=250, null=True)),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='project start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='project end date')),
                ('fund', models.IntegerField(blank=True, null=True, verbose_name='total amount of fund')),
            ],
        ),
    ]
