# Generated by Django 2.2.13 on 2020-08-05 20:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=64)),
                ('admin1', models.CharField(max_length=64)),
                ('admin2', models.CharField(max_length=64, null=True)),
                ('locality', models.CharField(max_length=86)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=10)),
                ('observation_date', models.DateField()),
                ('surveillance_type', models.CharField(max_length=20)),
                ('reporting_date', models.DateField()),
                ('diagnosis_status', models.CharField(max_length=20)),
                ('disease', models.CharField(max_length=40)),
                ('virus', models.CharField(max_length=5)),
                ('animal_type', models.CharField(max_length=25)),
                ('animal_class', models.CharField(max_length=25)),
                ('species', models.CharField(max_length=86, null=True)),
                ('at_risk', models.IntegerField(null=True)),
                ('cases', models.IntegerField(null=True)),
                ('deaths', models.IntegerField(null=True)),
                ('destroyed', models.IntegerField(null=True)),
                ('slaughtered', models.IntegerField(null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
