# Generated by Django 2.2.13 on 2020-08-05 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('text', models.TextField()),
                ('Photo', models.ImageField(blank=True, default='media/feedback/image5.jpg', null=True, upload_to='media/feedback')),
                ('Priority', models.CharField(choices=[('BU', 'Bug_urgent'), ('BNU', 'Bug_not_urgent'), ('FT', 'New feature'), ('UX', 'UX_urgent')], default='BNU', max_length=3)),
                ('feedback_date', models.DateField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Task_status',
            fields=[
                ('feedback_track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stats', serialize=False, to='feedback.Feedback')),
                ('assigned_to', models.CharField(choices=[('BR', 'Bhargav Bolla'), ('XJ', 'Xibei Jia')], default='XJ', max_length=2)),
                ('task_status', models.CharField(choices=[('CO', 'done'), ('WR', 'working'), ('NM', 'need more info'), ('NW', 'New')], default='NW', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment_text', models.TextField(blank=True)),
                ('Comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='feedback.Feedback')),
            ],
        ),
    ]
