# Generated by Django 2.2.13 on 2020-08-05 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('name', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('xdim', models.FloatField()),
                ('ydim', models.FloatField()),
                ('grid_size', models.FloatField()),
                ('projcode', models.IntegerField()),
                ('zonecode', models.IntegerField()),
                ('spherecode', models.IntegerField()),
                ('projparm', models.CharField(max_length=1000)),
                ('grid_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ordering', models.FloatField(blank=True, null=True)),
                ('long_name', models.CharField(blank=True, max_length=100, null=True)),
                ('short_name', models.CharField(blank=True, max_length=5, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('day_res', models.IntegerField(default=8)),
                ('is_global', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.IntegerField(null=True)),
                ('day', models.IntegerField(null=True)),
                ('timestamp', models.IntegerField()),
                ('absolute_path', models.CharField(default='N/A', max_length=300)),
                ('dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('long_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('name', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('upleftx', models.FloatField(null=True)),
                ('uplefty', models.FloatField(null=True)),
                ('lowrightx', models.FloatField(null=True)),
                ('lowrighty', models.FloatField(null=True)),
                ('iv', models.IntegerField()),
                ('ih', models.IntegerField()),
                ('lon_min', models.FloatField(null=True)),
                ('lon_max', models.FloatField(null=True)),
                ('lat_min', models.FloatField(null=True)),
                ('lat_max', models.FloatField(null=True)),
                ('continent', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True, verbose_name='date processed')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.File')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Product')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='products',
            field=models.ManyToManyField(through='inventory.Process', to='inventory.Product'),
        ),
        migrations.AddField(
            model_name='file',
            name='tile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Tile'),
        ),
    ]
