# Generated by Django 2.2.13 on 2021-05-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisday', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='lunch',
            field=models.CharField(max_length=4),
        ),
    ]
