# Generated by Django 3.2.4 on 2021-06-25 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gisday', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SurveyContent',
        ),
    ]
