# Generated by Django 2.2.13 on 2021-05-31 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisday', '0002_auto_20210531_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='v_info',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
