# Generated by Django 2.2.18 on 2021-06-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisday', '0002_aboutusgroup_aboutusperson_agenda_announcement_booth_boothcontent_committeecontent_gisdayphoto_itemd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='highest_degree',
            field=models.CharField(choices=[('High School', 'High School'), ('Associate', 'Associate'), ("Bachelor's", "Bachelor's"), ("Master's", "Master's"), ('Doctoral', 'Doctoral')], max_length=20, null=True, verbose_name='Highest Degree Obtained'),
        ),
    ]
