# Generated by Django 3.2.4 on 2021-06-25 23:42

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('gisday', '0002_delete_surveycontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField(blank=True, null=True)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gisday.year')),
            ],
            options={
                'unique_together': {('year',)},
            },
        ),
    ]
