# Generated by Django 3.2.4 on 2021-06-21 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gisday', '0002_aboutusgroup_aboutusperson_agenda_announcement_booth_boothcontent_committeecontent_gisdayphoto_itemd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gisdayphoto',
            name='picture',
            field=models.ImageField(null=True, upload_to='gisday/imagegallery/'),
        ),
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(null=True, upload_to='gisday/photogallery/')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gisday.year')),
            ],
        ),
    ]
