# Generated by Django 2.2.13 on 2021-05-31 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisday', '0003_volunteer_v_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='TShirtSize',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='prole',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
