# Generated by Django 2.2.18 on 2021-06-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisday', '0003_auto_20210617_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='highest_degree',
            field=models.CharField(max_length=20, null=True, verbose_name='Highest Degree Obtained'),
        ),
    ]
