# Generated by Django 3.2.4 on 2021-06-26 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gisday', '0003_surveycontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AboutUsPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('headshot', models.ImageField(default='gisday/aboutus/dummy_headshot222.jpg', null=True, upload_to='gisday/aboutus/')),
            ],
        ),
        migrations.CreateModel(
            name='PersonInGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pvsgInGroup', to='gisday.aboutusgroup')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pvsgInPerson', to='gisday.aboutusperson')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gisday.year')),
            ],
        ),
    ]
