# Generated by Django 3.2.4 on 2021-06-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisday', '0003_auto_20210621_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booth',
            name='names',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booth',
            name='oversized',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booth',
            name='permits',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
