# Generated by Django 3.2.4 on 2021-06-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisday', '0003_auto_20210621_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='verify_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
