# Generated by Django 2.2.18 on 2021-06-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisday', '0004_auto_20210617_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='parents_degree',
            field=models.CharField(choices=[('Neither', 'Neither my mother or father (neither of my guardians)'), ('Both', 'Both my mother and father (both my guardians)'), ('Father', 'Only my father (male guardian)'), ('Mother', 'Only my mother (female guardian)'), ("Don't know", 'I do not know'), ('NR', 'Prefer not to respond')], max_length=80, null=True, verbose_name='In your family, which of your parents/guardians received college degrees?'),
        ),
    ]
