# Generated by Django 3.2.4 on 2021-06-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisday', '0004_auto_20210622_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='verify_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='booth',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Questions & comments'),
        ),
        migrations.AlterField(
            model_name='booth',
            name='names',
            field=models.TextField(blank=True, null=True, verbose_name='Aditional atendees'),
        ),
        migrations.AlterField(
            model_name='booth',
            name='oversized',
            field=models.BooleanField(blank=True, null=True, verbose_name='Do you have a oversized exhibit or display?'),
        ),
        migrations.AlterField(
            model_name='booth',
            name='permits',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='No. of parking permits needed'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='validated',
            field=models.BooleanField(null=True),
        ),
    ]
