# Generated by Django 2.2.13 on 2021-05-31 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gisday', '0004_auto_20210531_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='v_info',
        ),
    ]
