# Generated by Django 3.2.4 on 2021-06-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisday', '0004_poster_verify_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='validated',
            field=models.BooleanField(null=True),
        ),
    ]
