# Generated by Django 2.2.18 on 2021-06-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisday', '0005_auto_20210617_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='citizenship',
            field=models.CharField(max_length=30, verbose_name='Citizenship'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='disability',
            field=models.CharField(max_length=50, verbose_name='Disability'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='ethnicity',
            field=models.CharField(max_length=20, verbose_name='Ethnicity'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='gender',
            field=models.CharField(max_length=20, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='institution',
            field=models.CharField(max_length=80, verbose_name='Participant Institution'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='parents_degree',
            field=models.CharField(max_length=80, null=True, verbose_name='In your family, which of your parents/guardians received college degrees?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='position',
            field=models.CharField(max_length=80, verbose_name='Participant Position'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='race',
            field=models.CharField(max_length=50, verbose_name='Race'),
        ),
    ]
