# Generated by Django 3.2.4 on 2021-06-25 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gisday', '0006_auto_20210624_0454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='verify_email',
        ),
        migrations.DeleteModel(
            name='LogisticsContent',
        ),
    ]
