# Generated by Django 3.2.4 on 2021-06-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisday', '0007_auto_20210617_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='oversized',
            field=models.BooleanField(blank=True, null=True, verbose_name='Do you have a oversized exhibit or display?'),
        ),
    ]
