# Generated by Django 3.2.4 on 2021-06-19 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gisday', '0008_alter_booth_oversized'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(null=True, upload_to='gisday/photo-gallery/')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gisday.year')),
            ],
        ),
    ]
