# Generated by Django 3.2.4 on 2021-06-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisday', '0009_photogallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photogallery',
            name='picture',
            field=models.ImageField(null=True, upload_to='gisday/gallery/'),
        ),
    ]
