# Generated by Django 3.2.4 on 2021-06-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisday', '0010_alter_photogallery_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gisdayphoto',
            name='picture',
            field=models.ImageField(null=True, upload_to='gisday/imagegallery/'),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='picture',
            field=models.ImageField(null=True, upload_to='gisday/photogallery/'),
        ),
    ]
