# Generated by Django 2.2.13 on 2020-08-05 20:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ceom.visualization.models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSeriesJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Additional sender')),
                ('points', models.FileField(max_length=150, upload_to='visualization/timeseries/input', validators=[ceom.visualization.models.checkFormat], verbose_name='Upload csv file')),
                ('result', models.FileField(blank=True, max_length=300, null=True, upload_to='visualization/timeseries/multi')),
                ('years', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Select years')),
                ('completed', models.BooleanField(default=False)),
                ('working', models.BooleanField(default=False)),
                ('error', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(blank=True, max_length=150, null=True)),
                ('task_id', models.CharField(blank=True, max_length=50, null=True)),
                ('total_sites', models.IntegerField(default=1)),
                ('progress', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Dataset')),
                ('user', models.ForeignKey(default=1096, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SingleTimeSeriesJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, max_length=50, null=True)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('row', models.IntegerField(blank=True, null=True)),
                ('col', models.IntegerField(blank=True, null=True)),
                ('tile', models.CharField(blank=True, max_length=6, null=True)),
                ('result', models.FileField(blank=True, max_length=300, null=True, upload_to='visualization/timeseries/single')),
                ('years', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Select years')),
                ('completed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Dataset')),
                ('user', models.ForeignKey(default=1096, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
