# Generated by Django 3.2.15 on 2022-11-27 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='file',
        ),
        migrations.RemoveField(
            model_name='process',
            name='product',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Process',
        ),
    ]
