# Generated by Django 3.2.12 on 2022-03-27 18:38

import ceom.modis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singletimeseriesjob',
            name='result',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='timeseries/single'),
        ),
        migrations.AlterField(
            model_name='timeseriesjob',
            name='points',
            field=models.FileField(max_length=150, upload_to='timeseries/input', validators=[ceom.modis.models.checkFormat], verbose_name='Upload csv file'),
        ),
        migrations.AlterField(
            model_name='timeseriesjob',
            name='result',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='timeseries/multi'),
        ),
    ]
