# Generated by Django 3.2.16 on 2022-12-20 09:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modis', '0002_auto_20221127_2241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tile',
        ),
        migrations.RenameField(
            model_name='modismultipletimeseriesjob',
            old_name='error',
            new_name='errored',
        ),
        migrations.RemoveField(
            model_name='modismultipletimeseriesjob',
            name='message',
        ),
        migrations.RemoveField(
            model_name='modismultipletimeseriesjob',
            name='product',
        ),
        migrations.RemoveField(
            model_name='modismultipletimeseriesjob',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='modismultipletimeseriesjob',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='modismultipletimeseriesjob',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='modismultipletimeseriesjob',
            name='total_sites',
        ),
        migrations.RemoveField(
            model_name='modissingletimeseriesjob',
            name='col',
        ),
        migrations.RemoveField(
            model_name='modissingletimeseriesjob',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='modissingletimeseriesjob',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='modissingletimeseriesjob',
            name='product',
        ),
        migrations.RemoveField(
            model_name='modissingletimeseriesjob',
            name='row',
        ),
        migrations.RemoveField(
            model_name='modissingletimeseriesjob',
            name='tile',
        ),
        migrations.AddField(
            model_name='modismultipletimeseriesjob',
            name='percent_complete',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modissingletimeseriesjob',
            name='errored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modissingletimeseriesjob',
            name='h',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modissingletimeseriesjob',
            name='percent_complete',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modissingletimeseriesjob',
            name='v',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modissingletimeseriesjob',
            name='working',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modissingletimeseriesjob',
            name='x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modissingletimeseriesjob',
            name='y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modismultipletimeseriesjob',
            name='points',
            field=models.FileField(max_length=150, upload_to='modis/timeseries/multi/input/'),
        ),
        migrations.AlterField(
            model_name='modismultipletimeseriesjob',
            name='result',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='modis/timeseries/multi/output/'),
        ),
        migrations.AlterField(
            model_name='modismultipletimeseriesjob',
            name='years',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=4), size=None),
        ),
        migrations.AlterField(
            model_name='modissingletimeseriesjob',
            name='years',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=4), size=None),
        ),
    ]
