# Generated by Django 3.2.12 on 2022-04-25 14:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('modis', '0003_auto_20220327_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeseriesjob',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeseriesjob',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
