# Generated by Django 3.2.12 on 2022-05-07 21:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modis', '0004_auto_20220425_1440'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeSeriesJob',
            new_name='MODISMultipleTimeSeriesJob',
        ),
        migrations.RenameModel(
            old_name='SingleTimeSeriesJob',
            new_name='MODISSingleTimeSeriesJob',
        ),
    ]
