# Generated by Django 3.2.15 on 2022-08-27 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modis', '0005_auto_20220507_2159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeocatterPoint',
        ),
    ]
