# Generated by Django 2.2.13 on 2020-08-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='phenocam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(blank=True, max_length=50)),
                ('takendate', models.DateTimeField(blank=True, null=True)),
                ('red', models.DecimalField(blank=True, decimal_places=18, max_digits=20, null=True)),
                ('green', models.DecimalField(blank=True, decimal_places=18, max_digits=20, null=True)),
                ('blue', models.DecimalField(blank=True, decimal_places=18, max_digits=20, null=True)),
                ('gcc', models.DecimalField(blank=True, decimal_places=18, max_digits=20, null=True)),
            ],
        ),
    ]
