# Generated by Django 3.2.4 on 2021-07-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_dataset_projparm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.BigIntegerField(),
        ),
    ]
