# Generated by Django 3.2.4 on 2021-07-20 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20210720_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.file'),
        ),
        migrations.AlterField(
            model_name='process',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.product'),
        ),
    ]
