# Generated by Django 3.2.4 on 2021-07-11 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_auto_20210610_0039'),
        ('visualization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeocatterPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_categorized', models.DateField(auto_now_add=True)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.category')),
            ],
            options={
                'unique_together': {('date_categorized', 'lat', 'lon')},
            },
        ),
    ]
