# Generated by Django 3.2.4 on 2021-07-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0002_geocatterpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geocatterpoint',
            name='date_categorized',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
