# Generated by Django 3.2.4 on 2021-07-11 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0003_alter_geocatterpoint_date_categorized'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='geocatterpoint',
            unique_together=set(),
        ),
    ]
