# Generated by Django 3.2.4 on 2021-07-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0004_alter_geocatterpoint_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geocatterpoint',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
