# Generated by Django 2.2.13 on 2020-08-05 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Country')),
                ('affiliation', models.CharField(blank=True, max_length=250, null=True, verbose_name='Affiliation')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telephone')),
                ('address1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Address1')),
                ('address2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Address2')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=80, null=True, verbose_name='State')),
                ('postal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Postal code')),
                ('url', models.CharField(blank=True, max_length=100, null=True, verbose_name='URL')),
                ('gisday', models.NullBooleanField(verbose_name='Attending GIS Day')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
