# Generated by Django 3.2.4 on 2021-06-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gisday',
            field=models.BooleanField(blank=True, null=True, verbose_name='Attending GIS Day'),
        ),
    ]
