# Generated by Django 3.2.4 on 2021-07-05 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photos', '0009_auto_20210610_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pixel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h', models.IntegerField()),
                ('v', models.IntegerField()),
                ('col', models.IntegerField()),
                ('row', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PixelDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pixel_resolution', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('ncol', models.IntegerField()),
                ('nrow', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PixelValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_done', models.DateField(auto_now=True)),
                ('date_of_map', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('photo_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photos.photo')),
                ('pixel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poi.pixel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pixel',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poi.pixeldataset'),
        ),
        migrations.CreateModel(
            name='ResearchPixel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_id', models.CharField(blank=True, max_length=30, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('pixel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poi.pixel')),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poi.research')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('pixel', 'research')},
            },
        ),
        migrations.CreateModel(
            name='PixelValidationLandcover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.category')),
                ('validation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poi.pixelvalidation')),
            ],
            options={
                'unique_together': {('validation', 'category')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='pixel',
            unique_together={('h', 'v', 'col', 'row', 'dataset')},
        ),
    ]
