# Generated by Django 2.2.13 on 2020-08-04 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisday', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusperson',
            name='headshot',
            field=models.ImageField(default='gisday/aboutus/dummy_headshot222.jpg', null=True, upload_to='gisday/aboutus/'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gisday/announcements/'),
        ),
        migrations.AlterField(
            model_name='booth',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Questions & comments'),
        ),
        migrations.AlterField(
            model_name='booth',
            name='names',
            field=models.TextField(blank=True, null=True, verbose_name='Aditional atendees'),
        ),
        migrations.AlterField(
            model_name='booth',
            name='oversized',
            field=models.NullBooleanField(verbose_name='Do you have a oversized exhibit or display?'),
        ),
        migrations.AlterField(
            model_name='booth',
            name='permits',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='No. of parking permits needed'),
        ),
        migrations.AlterField(
            model_name='booth',
            name='tshirt_size_1',
            field=models.CharField(choices=[('UK', 'Unkown'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('2XL', 'Extra Extra Large')], max_length=3),
        ),
        migrations.AlterField(
            model_name='booth',
            name='tshirt_size_2',
            field=models.CharField(choices=[('UK', 'Unkown'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('2XL', 'Extra Extra Large')], max_length=3),
        ),
        migrations.AlterField(
            model_name='boothcontent',
            name='registration_recipients',
            field=models.CharField(default='gisday@ou.edu', max_length=600),
        ),
        migrations.AlterField(
            model_name='demographicsurvey',
            name='citizenship',
            field=models.CharField(choices=[('US Citizen', 'US Citizen'), ('Permanent Resident', 'Permanent Resident'), ('Non-Us Citizen', 'Non-Us Citizen'), ('NR', 'Prefer not to respond')], max_length=30, verbose_name='Citizenship'),
        ),
        migrations.AlterField(
            model_name='demographicsurvey',
            name='disability',
            field=models.CharField(choices=[('Hearing Impairment', 'Hearing Impairment'), ('Mobility/Orthopedic impairment', 'Mobility/Orthopedic impairment'), ('Visual Impairment', 'Visual Impairment'), ('None', 'None'), ('Prefer not to respond', 'Prefer not to respond'), ('Other', 'Other (please specify)')], max_length=50, verbose_name='Disability'),
        ),
        migrations.AlterField(
            model_name='demographicsurvey',
            name='ethnicity',
            field=models.CharField(choices=[('Hispanic/Latino', 'Hispanic/Latino'), ('Not Hispanic/Latino', 'Not Hispanic/Latino'), ('NR', 'Prefer not to respond')], max_length=20, verbose_name='Ethnicity'),
        ),
        migrations.AlterField(
            model_name='demographicsurvey',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('NR', 'Prefer not to respond')], max_length=20, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='demographicsurvey',
            name='highest_degree',
            field=models.CharField(choices=[('High School', 'High School'), ('Associate', 'Associate'), ("Bachelor's", "Bachelor's"), ("Master's", "Master's"), ('Doctoral', 'Doctoral')], max_length=20, verbose_name='Highest Degree Obtained'),
        ),
        migrations.AlterField(
            model_name='demographicsurvey',
            name='institution',
            field=models.CharField(choices=[('Oklahoma State University', 'Oklahoma State University'), ('Samuel Roberts Noble Foundation', 'Samuel Roberts Noble Foundation'), ('University of Oklahoma', 'University of Oklahoma'), ('University of Tulsa', 'University of Tulsa'), ('Other', 'Other please specify')], max_length=80, verbose_name='Participant Institution'),
        ),
        migrations.AlterField(
            model_name='demographicsurvey',
            name='other_disability',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='If other, please specify'),
        ),
        migrations.AlterField(
            model_name='demographicsurvey',
            name='other_institution',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='If other, please specify'),
        ),
        migrations.AlterField(
            model_name='demographicsurvey',
            name='other_position',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='If other, please specify'),
        ),
        migrations.AlterField(
            model_name='demographicsurvey',
            name='other_race',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='If other, please specify'),
        ),
        migrations.AlterField(
            model_name='demographicsurvey',
            name='parents_degree',
            field=models.CharField(choices=[('Neither', 'Neither my mother or father (neither of my guardians)'), ('Both', 'Both my mother and father (both my guardians)'), ('Father', 'Only my father (male guardian)'), ('Mother', 'Only my mother (female guardian)'), ("Don't know", 'I do not know'), ('NR', 'Prefer not to respond')], max_length=80, verbose_name='In your family, which of your parents/guardians received college degrees?'),
        ),
        migrations.AlterField(
            model_name='demographicsurvey',
            name='position',
            field=models.CharField(choices=[('Community College Faculty', 'Community College Faculty'), ('Doctoral Student', 'Doctoral Student'), ('EPSCoR Staff', 'EPSCoR Staff'), ('Government Staff', 'Government Staff'), ('Graduate Faculty', 'Graduate Faculty'), ('Higher Education Faculty', 'Higher Education Faculty'), ('K-12 Administrator', 'K-12 Administrator'), ('K-12 Teacher', 'K-12 Teacher'), ('K-12 Student', 'K-12 Student'), ("Master's Student", "Master's Student"), ('Other Pre-College Teachers', 'Other Pre-College Teachers'), ('Post-Doctoral Researcher', 'Post-Doctoral Researcher'), ('Researcher', 'Researcher'), ('REU Participant', 'REU Participant'), ('Technical School Faculty', 'Technical School Faculty'), ('Technical School Student', 'Technical School Student'), ('Staff - Technical', 'Staff - Technical'), ('Staff - Non-Technical', 'Staff - Non-Technical'), ('Undergraduate Faculty', 'Undergraduate Faculty'), ('Undergraduate Student', 'Undergraduate Student'), ('Other', 'Other please specify')], max_length=80, verbose_name='Participant Position'),
        ),
        migrations.AlterField(
            model_name='demographicsurvey',
            name='race',
            field=models.CharField(choices=[('American Indian or Alaskan Native', 'American Indian or Alaskan Native'), ('Asian', 'Asian'), ('Black or African American ', 'Black or African American '), ('Native Hawaiian or Pacific Islander', 'Native Hawaiian or Pacific Islander'), ('White', 'White'), ('Prefer not to respond', 'Prefer not to respond'), ('Other', 'Other (please specify)')], max_length=50, verbose_name='Race'),
        ),
        migrations.AlterField(
            model_name='gisdayphoto',
            name='picture',
            field=models.ImageField(null=True, upload_to='gisday/gallery/'),
        ),
        migrations.AlterField(
            model_name='itemdonor',
            name='logo',
            field=models.ImageField(null=True, upload_to='gisday/item_donors/'),
        ),
        migrations.AlterField(
            model_name='overviewimage',
            name='image',
            field=models.ImageField(upload_to='gisday/overview/'),
        ),
        migrations.AlterField(
            model_name='photocontestparticipant',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Questions & comments'),
        ),
        migrations.AlterField(
            model_name='photocontestparticipant',
            name='email',
            field=models.EmailField(max_length=60, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='photocontestparticipant',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='photocontestparticipant',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='abstract',
            field=models.TextField(verbose_name='Poster abstract'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='authors',
            field=models.TextField(blank=True, null=True, verbose_name='Poster author list'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Questions & comments'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='preview',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='gisday/posters/'),
        ),
        migrations.AlterField(
            model_name='postercontestcontent',
            name='registration_recipients',
            field=models.CharField(default='gisday@ou.edu', max_length=600),
        ),
        migrations.AlterField(
            model_name='sponsorcategory',
            name='logo',
            field=models.ImageField(null=True, upload_to='gisday/sponsors/'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='beneficial_aspects',
            field=models.TextField(verbose_name='What was the most beneficial or interesting aspect of the event?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='comments_and_suggestions',
            field=models.TextField(blank=True, null=True, verbose_name='Please provide any additional comments or suggestions:'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='other_role',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='If other, please specify'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='participate_again',
            field=models.BooleanField(verbose_name='I would like to participate in the event again'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='role',
            field=models.CharField(choices=[('Organizing Committee', 'Organizing Committee'), ('Faculty Poster Judge', 'Faculty Poster Judge'), ('Student Poster Contestant', 'Student Poster Contestant'), ('Booth Exhibitor', 'Booth Exhibitor'), ('Poster Exhibitor', 'Poster Exhibitor'), ('Student Facilitator/Volunteer', 'Student Facilitator/Volunteer'), ('Staff Facilitator', 'Staff Facilitator'), ('Other', 'Other (please specify)')], max_length=50, verbose_name='What was you primary role in the event?'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Questions & comments'),
        ),
        migrations.AlterField(
            model_name='visitorregistrationcontent',
            name='registration_recipients',
            field=models.CharField(default='gisday@ou.edu', max_length=600),
        ),
    ]
