# Generated by Django 2.2.13 on 2020-08-05 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='roi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('tile', models.CharField(blank=True, max_length=6, null=True)),
                ('image', models.ImageField(blank=True, default='media/feedback/image5.jpg', null=True, upload_to='media/roi')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('classification', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('pixelsize', models.IntegerField()),
                ('col', models.IntegerField(blank=True, null=True)),
                ('row', models.IntegerField(blank=True, null=True)),
                ('points', models.TextField()),
                ('category', models.ForeignKey(blank=True, db_column='categoryid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rois', to='photos.Category')),
                ('user', models.ForeignKey(default=1096, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='poi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('score', models.IntegerField(blank=True, null=True)),
                ('Attribute', models.TextField(verbose_name='Attributes')),
                ('classification', models.CharField(blank=True, max_length=500, null=True, verbose_name='Site Category')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('category', models.ForeignKey(blank=True, db_column='categoryid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pois', to='photos.Category')),
                ('user', models.ForeignKey(default=1829, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='map_gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_image', models.ImageField(default='media/feedback/image5.jpg', upload_to='media/map_gallery', verbose_name='Upload Map')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('description', models.TextField(verbose_name='Description')),
                ('title', models.CharField(max_length=3000, verbose_name='Title of your map')),
                ('name_uploader', models.CharField(max_length=3000, verbose_name='Your Name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('validated', models.BooleanField()),
                ('map_image_legend', models.ImageField(default='media/feedback/image5.jpg', upload_to='media/map_gallery', verbose_name='Legend')),
                ('user', models.ForeignKey(default=1829, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_comment', models.CharField(max_length=3000, verbose_name='Your Name')),
                ('Comment_text', models.TextField(verbose_name='Enter Comment here')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('Comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='maps.map_gallery')),
            ],
        ),
    ]
