# Generated by Django 3.2.15 on 2022-08-27 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0012_REGISTER_ORIGINAL_VOTES'),
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeocatterPoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_categorized', models.DateTimeField(auto_now_add=True)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.category')),
            ],
        ),
        migrations.RemoveField(
            model_name='map_gallery',
            name='user',
        ),
        migrations.RemoveField(
            model_name='poi',
            name='category',
        ),
        migrations.RemoveField(
            model_name='poi',
            name='user',
        ),
        migrations.RemoveField(
            model_name='roi',
            name='category',
        ),
        migrations.RemoveField(
            model_name='roi',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='map_gallery',
        ),
        migrations.DeleteModel(
            name='poi',
        ),
        migrations.DeleteModel(
            name='roi',
        ),
    ]
