# Generated by Django 3.2.15 on 2022-09-11 16:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0012_REGISTER_ORIGINAL_VOTES'),
        ('maps', '0002_auto_20220827_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geocatterpoint',
            name='category',
        ),
        migrations.RemoveField(
            model_name='geocatterpoint',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='geocatterpoint',
            name='lon',
        ),
        migrations.AddField(
            model_name='geocatterpoint',
            name='date_taken',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geocatterpoint',
            name='grid_npix',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geocatterpoint',
            name='is_multi_cat',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geocatterpoint',
            name='pixel_x',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geocatterpoint',
            name='pixel_y',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geocatterpoint',
            name='primary_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='primary_category', to='photos.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geocatterpoint',
            name='secondary_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_category', to='photos.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geocatterpoint',
            name='tile_h',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geocatterpoint',
            name='tile_v',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
