# Generated by Django 3.2.15 on 2022-09-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20220911_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geocatterpoint',
            name='date_categorized',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='geocatterpoint',
            name='date_taken',
            field=models.DateField(),
        ),
    ]
