# Generated by Django 3.2.15 on 2022-12-24 14:02

import django.contrib.gis.db.models.fields
from django.db import migrations
from django.contrib.gis.geos import Point


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_geocatterpoint_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='geocatterpoint',
            name='center',
            field=django.contrib.gis.db.models.fields.PointField(default=Point(0,0), srid=4326),
            preserve_default=False,
        ),
    ]
