# Generated by Django 2.2.13 on 2021-05-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_remove_workshopregistration_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopregistration',
            name='validated',
            field=models.BooleanField(null=True),
        ),
    ]
