# Generated by Django 2.2.13 on 2021-05-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0004_workshopregistration_validated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopregistration',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
