# Generated by Django 3.2.4 on 2021-06-27 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0005_auto_20210525_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopregistration',
            name='verify_email',
        ),
    ]
