# Generated by Django 2.2.13 on 2020-08-04 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryphoto',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='picture',
            field=models.ImageField(upload_to='aboutus/group_photos/photos'),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='person',
            name='date',
            field=models.DateField(null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='person',
            name='headshot',
            field=models.ImageField(default='/media/people/dummy_headshot222.jpg', null=True, upload_to='people/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_comlumn_number',
            field=models.CharField(choices=[('1', 'One column image'), ('2', 'Two columns image')], default='1', max_length=1, verbose_name=' column images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(verbose_name='Post Title'),
        ),
        migrations.AlterField(
            model_name='postfile',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='postfile',
            name='file_attached',
            field=models.FileField(upload_to='news/docs'),
        ),
        migrations.AlterField(
            model_name='postfile',
            name='title',
            field=models.CharField(max_length=80, verbose_name='File title'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(null=True, upload_to='news'),
        ),
    ]
