# Generated by Django 2.2.13 on 2020-08-04 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0009_poi_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Comment_text',
            field=models.TextField(verbose_name='Enter Comment here'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name_comment',
            field=models.CharField(max_length=3000, verbose_name='Your Name'),
        ),
        migrations.AlterField(
            model_name='map_gallery',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='map_gallery',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='map_gallery',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='map_gallery',
            name='map_image',
            field=models.ImageField(default='media/feedback/image5.jpg', upload_to='media/map_gallery', verbose_name='Upload Map'),
        ),
        migrations.AlterField(
            model_name='map_gallery',
            name='map_image_legend',
            field=models.ImageField(default='media/feedback/image5.jpg', upload_to='media/map_gallery', verbose_name='Legend'),
        ),
        migrations.AlterField(
            model_name='map_gallery',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='map_gallery',
            name='name_uploader',
            field=models.CharField(max_length=3000, verbose_name='Your Name'),
        ),
        migrations.AlterField(
            model_name='map_gallery',
            name='title',
            field=models.CharField(max_length=3000, verbose_name='Title of your map'),
        ),
        migrations.AlterField(
            model_name='poi',
            name='Attribute',
            field=models.TextField(verbose_name='Attributes'),
        ),
        migrations.AlterField(
            model_name='poi',
            name='category',
            field=models.ForeignKey(blank=True, db_column='categoryid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pois', to='photos.Category'),
        ),
        migrations.AlterField(
            model_name='poi',
            name='classification',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Site Category'),
        ),
        migrations.AlterField(
            model_name='poi',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='poi',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='roi',
            name='category',
            field=models.ForeignKey(blank=True, db_column='categoryid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rois', to='photos.Category'),
        ),
        migrations.AlterField(
            model_name='roi',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='roi',
            name='image',
            field=models.ImageField(blank=True, default='media/feedback/image5.jpg', null=True, upload_to='media/roi'),
        ),
        migrations.AlterField(
            model_name='roi',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
